#!/bin/sh
source "../../common/init.sh"

get https://github.com/embree/embree/archive/v${PV}.tar.gz
acheck

importpkg media-libs/libpng media-libs/libjpeg-turbo gl dev-libs/imath

cd "${T}"

CMAKEOPTS=(
	-DTBB_ROOT=/pkg/main/dev-cpp.tbb.dev
	-DOPENIMAGEIO_ROOT=/pkg/main/media-libs.openimageio.dev
	-DBUILD_TESTING:BOOL=OFF
	-DCMAKE_SKIP_INSTALL_RPATH:BOOL=ON
	-DEMBREE_BACKFACE_CULLING=OFF
	-DEMBREE_COMPACT_POLYS=ON
	-DEMBREE_FILTER_FUNCTION=ON
	-DEMBREE_GEOMETRY_CURVE=ON
	-DEMBREE_GEOMETRY_GRID=ON
	-DEMBREE_GEOMETRY_INSTANCE=ON
	-DEMBREE_GEOMETRY_POINT=ON
	-DEMBREE_GEOMETRY_QUAD=ON
	-DEMBREE_GEOMETRY_SUBDIVISION=ON
	-DEMBREE_GEOMETRY_TRIANGLE=ON
	-DEMBREE_GEOMETRY_USER=ON
	-DEMBREE_IGNORE_CMAKE_CXX_FLAGS=OFF
	-DEMBREE_IGNORE_INVALID_RAYS=OFF
	-DEMBREE_ISPC_SUPPORT=OFF # ispc doesn't build because of llvm
	-DEMBREE_RAY_MASK=ON
	-DEMBREE_RAY_PACKETS=ON
	-DEMBREE_STACK_PROTECTOR=ON
	-DEMBREE_STATIC_LIB=ON
	-DEMBREE_STAT_COUNTERS=OFF
	-DEMBREE_TASKING_SYSTEM:STRING=TBB
	-DEMBREE_TUTORIALS=ON

	#-DEMBREE_ISPC_ADDRESSING:STRING="64"
	-DEMBREE_TUTORIALS_LIBJPEG=ON
	-DEMBREE_TUTORIALS_LIBPNG=ON
	-DEMBREE_TUTORIALS_OPENIMAGEIO=ON
)

docmake "${CMAKEOPTS[@]}"

finalize
