#!/bin/sh
source "../../common/init.sh"

#get https://github.com/libjxl/libjxl/archive/refs/tags/v${PV}.tar.gz ${P}.tar.gz
get https://api.github.com/repos/libjxl/libjxl/tarball/105bf1a20be35c2d0d7dd302c008f3669c2f998c ${P}.tar.gz
acheck

importpkg dev-cpp/highway lcms2 dev-cpp/gflags

cd "${T}"

CMAKEOPTS=(
	-DBUILD_TESTING=OFF
	-DJPEGXL_ENABLE_BENCHMARK=OFF
	-DJPEGXL_ENABLE_COVERAGE=OFF
	-DJPEGXL_ENABLE_FUZZERS=OFF
	-DJPEGXL_ENABLE_SJPEG=OFF
	-DJPEGXL_WARNINGS_AS_ERRORS=OFF

	-DJPEGXL_ENABLE_SKCMS=OFF
	-DJPEGXL_ENABLE_VIEWERS=OFF
	-DJPEGXL_ENABLE_PLUGINS=OFF
	-DJPEGXL_FORCE_SYSTEM_BROTLI=ON
	-DJPEGXL_FORCE_SYSTEM_HWY=ON
	-DJPEGXL_FORCE_SYSTEM_LCMS2=ON
	-DJPEGXL_ENABLE_DOXYGEN=OFF
	-DJPEGXL_ENABLE_MANPAGES=OFF
	-DJPEGXL_ENABLE_JNI=OFF
	-DJPEGXL_ENABLE_TCMALLOC=OFF
	-DJPEGXL_ENABLE_EXAMPLES=OFF

	-DJPEGXL_ENABLE_TOOLS=ON
	-DJPEGXL_ENABLE_OPENEXR=ON
)

docmake "${CMAKEOPTS[@]}"

finalize
