#!/bin/sh
source "../../common/init.sh"
inherit python

PYTHON_RESTRICT="$PYTHON_LATEST"

PN=pytorch PKG=sci-libs.pytorch get https://github.com/pytorch/pytorch/releases/download/v${PV}/pytorch-v${PV}.tar.gz pytorch-${PV}.tar.gz

acheck

cd "${T}"

OPTS=(
	-DBUILD_CUSTOM_PROTOBUF=OFF
	-DBUILD_SHARED_LIBS=ON

	-DUSE_CCACHE=OFF
	-DUSE_CUDA=ON
	-DUSE_CUDNN=ON
	-DUSE_FAST_NVCC=ON
	#-DTORCH_CUDA_ARCH_LIST="3.5 7.0"
	-DBUILD_NVFUSER=OFF
	# -DUSE_DISTRIBUTED=ON # todo tensorpipe
	-DUSE_MPI=OFF # openmpi + ensorpipe etc
	-DUSE_FAKELOWP=OFF
	#-DUSE_FBGEMM=
	-DUSE_FFMPEG=ON
	-DUSE_GFLAGS=ON
	-DUSE_GLOG=ON
	-DUSE_GLOO=OFF
	-DUSE_KINETO=OFF # TODO
	-DUSE_LEVELDB=OFF
	-DUSE_MAGMA=OFF # TODO: In GURU as sci-libs/magma
	-DUSE_MKLDNN=OFF
	-DUSE_NCCL=OFF # TODO: NVIDIA Collective Communication Library

	# TODO
	-DUSE_NNPACK=OFF
	-DUSE_QNNPACK=OFF
	-DUSE_XNNPACK=OFF
	-DUSE_SYSTEM_XNNPACK=OFF
	-DUSE_TENSORPIPE=OFF
	-DUSE_PYTORCH_QNNPACK=OFF

	-DUSE_NUMPY=ON
	-DUSE_OPENCL=ON
	-DUSE_OPENCV=ON
	-DUSE_OPENMP=ON
	-DUSE_ROCM=OFF # TODO
	-DUSE_SYSTEM_CPUINFO=ON
	-DUSE_SYSTEM_PYBIND11=ON
	-DUSE_UCC=OFF
	-DUSE_VALGRIND=OFF
	-DPYBIND11_PYTHON_VERSION="$PYTHON_LATEST"
	-DPYTHON_EXECUTABLE="python${PYTHON_LATEST%.*}"
	-DUSE_ITT=OFF
	-DBLAS=Eigen # avoid the use of MKL, if found on the system
	-DUSE_SYSTEM_EIGEN_INSTALL=ON
	-DUSE_SYSTEM_PTHREADPOOL=ON
	-DUSE_SYSTEM_FXDIV=ON
	-DUSE_SYSTEM_FP16=ON
	-DUSE_SYSTEM_GLOO=ON
	-DUSE_SYSTEM_ONNX=ON
	-DUSE_SYSTEM_SLEEF=ON

	-Wno-dev
	-DTORCH_INSTALL_LIB_DIR="/pkg/main/${PKG}.libs.${PVRF}/lib$LIB_SUFFIX"
	-DLIBSHM_INSTALL_LIB_SUBDIR="/pkg/main/${PKG}.libs.${PVRF}/lib$LIB_SUFFIX"

	# -DCMAKE_CUDA_FLAGS=""
)

docmake "${OPTS[@]}"

finalize
